# -*- coding: utf-8 -*-
"""lint：标题与钩子检查（A5 + A6）

背景（来自大纲「账号级约束」）：
  公众号已进入算法推荐时代，选题普适性决定入池 —— 「大基数人群+具体场景痛点」
  远胜「影子价格理论」。**每章标题必须场景化翻译，体系术语只进正文。**
  前 200 字定生死 —— 开头若以定义/理论切入，读者在读完概念前就划走。

检查项：
  A5 钩子   开头 200 字是否以定义/理论开头（应为具体场景或人物处境）
  A6 标题   标题是否场景化（含具体处境而非纯体系术语）
  附加      AI 生成标注检测（大纲要求标注）

判定哲学
--------
与 audit.py 一致：**宁可多报，不可漏报**。检查器的作用是提醒作者复核，
不是替作者做文学判断，因此只给「风险信号」，不给「判决」。

语料依据（从现有 10 篇文档反推，非凭空设定）：
  好标题：月薪两万的 996 / 烧掉的桥 / 六千公里 / 一份 1.12 分的 offer
          → 含具体数字、具体处境、第一人称动作
  差标题：职业凯利公式 / 影子价格
          → 纯体系术语，无处境

用法：
  python tools/lint.py                    # 全库检查
  python tools/lint.py <文件>             # 单文件
  python tools/lint.py --json             # 机器可读
"""
import re
import sys
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"

HOOK_WINDOW = 200# 开头多少字算「钩子区」

# ── 体系术语表：出现在标题里即扣分 ─────────────────────────
# 来自项目自身的理论词。原则：术语进正文，不进标题。
SYSTEM_TERMS = [
    "凯利", "凯利公式", "影子价格", "期望值", "期望分", "概率", "数学模型",
    "决策模型", "模型", "公式", "理论", "框架", "体系", "量化", "参数",
    "五参数", "权重", "刻度", "口径", "复利性", "可逆性", "机会成本",
    "分母", "分子", "算法", "逻辑", "机制", "原理", "方法论", "博弈",
]

# ── 场景化信号：标题含这些才可能成立 ───────────────────────
SCENE_SIGNALS = [
    r"\d",                # 含数字（1.12 / 20% / 996 / 六千）
    r"我|你|他|她",                # 第一/第二人称
    r"offer|工作|岗位|面试|裸辞|跳槽|入职|辞职|裁员|涨薪|降薪",
    r"公里|时差|海外|境外|银行|体制内|大厂|国企|外企",
    r"为什么|怎么|如何|该不该|要不要|值不值",
    r"丢了|捡了|烧掉|错过|后悔|算了|算清|算漏",
    r"？|\?",# 设问
]

# ── 钩子区禁止的开篇模式 ───────────────────────────────────
# 以定义/理论切入的典型写法
DEFINITION_PATTERNS = [
    (r"^#{1,6}\s*[^#]*?(定义|概念|什么是|原理|概述|简介|绪论|背景|理论)", "以「定义/原理/概述」类标题开篇"),
    (r"^\s*(?:本文|本篇|下面|接下来)[^。]{0,20}(将|会|来)?(介绍|讲述|说明|讨论|分析|探讨)", "以「本文将介绍…」开篇，直接宣告而非场景切入"),
    (r"^[^。]{0,30}(是指|指的是|称为|叫做)[^。]{0,20}", "开篇即给概念定义"),
    (r"^[^。]{0,20}(所谓的?|一般而言|通常而言|一般来说)", "以泛论语气开篇，非具体处境"),
]

# 明确的 AI 生成标注
AI_MARKERS = [
    "本文由AI生成", "AI生成", "本文由 AI 生成", "Generated by AI",
    "人工智能生成", "AI 撰写", "AI撰写", "由ChatGPT", "由 GPT",
]

# ── 提示信息：开篇若是引用/口径说明，允许跳过（属体例前置） ──
FRONTMATTER_HINT = [
    "《", ">", "CC BY", "口径说明", "本案例演示", "分值系发布时",
]


class Issue:
    def __init__(self, kind, level, path, line, msg, detail=""):
        self.kind = kind        # hook | title | ai_tag
        self.level = level      # high | medium
        self.path = path
        self.line = line
        self.msg = msg
        self.detail = detail

    def ref(self):
        try:
            rel = Path(self.path).relative_to(ROOT)
        except ValueError:
            rel = Path(self.path)
        return f"{rel}:{self.line}"

    def as_dict(self):
        return {"kind": self.kind, "level": self.level, "ref": self.ref(),
                "msg": self.msg, "detail": self.detail}


def get_title(lines):
    """取文档标题：首个一级标题"""
    for i, l in enumerate(lines, 1):
        if l.startswith("# "):
            return l[2:].strip(), i
    return "", 1


def get_hook_text(lines):
    """取开头钩子文本。

    规则：
    - 跳过一级标题（承载标题）与引用块（体例前置，不算钩子）
    - 遇到任何标题（## / ###）立即结束 —— 钩子只算标题之前那段
    - 空行：开头可跳过（前置换行），正文开始后即结束
    """
    out = []
    seen_body = False
    for l in lines:
        s = l.strip()
        if s.startswith("# "):# 一级标题：跳过
            continue
        if s.startswith(">"):        # 引用块：体例前置，跳过
            continue
        if s.startswith("#"):        # 二级及以下标题：钩子区到此结束
            break
        if not s:
            if seen_body:
                break                 # 正文中的空行 → 钩子结束
            continue# 开头空行：跳过
        out.append(s)
        seen_body = True
    return " ".join(out)


def check_title(path, title, lines):
    """A6 标题场景化检查"""
    issues = []
    if not title:
        issues.append(Issue("title", "high", path, 1, "缺少一级标题", "文档无 `# ` 开头的标题"))
        return issues

    t = title

    # 纯术语标题：既无场景信号，又含体系术语
    has_scene = any(re.search(p, t) for p in SCENE_SIGNALS)
    hits = [w for w in SYSTEM_TERMS if w in t]
    if hits and not has_scene:
        issues.append(Issue(
            "title", "high", path, 1,
            f"标题是纯体系术语，未做场景化翻译",
            f"含术语「{'、'.join(hits)}」且无任何场景信号（数字/第一人称/具体处境）",
        ))
    elif hits:
        issues.append(Issue(
            "title", "medium", path, 1,
            "标题含体系术语",
            f"含「{'、'.join(hits)}」——大纲要求术语只进正文，建议换成场景说法",
        ))

    # 场景信号密度：标题应同时具备「具体处境」与「提问/判断」
    if not has_scene:
        issues.append(Issue(
            "title", "medium", path, 1,
            "标题缺少具体处境",
            "未见数字、第一人称或具体职业/场景词，算法推荐下难以入池",
        ))
    return issues


def check_hook(path, lines):
    """A5 开头 200 字检查"""
    issues = []
    hook = get_hook_text(lines)
    if not hook:
        return issues

    window = hook[:HOOK_WINDOW]

    for pat, why in DEFINITION_PATTERNS:
        if re.search(pat, window):
            line_no = 1
            for i, l in enumerate(lines, 1):
                if l.strip() and not l.startswith((">", "#")):
                    line_no = i
                    break
            issues.append(Issue(
                "hook", "high", path, line_no,
                f"开头以定义/理论切入：{why}",
                f"钩子区前 {HOOK_WINDOW} 字内命中「{why}」——大纲要求先给场景再给概念",
            ))
            break

    # 钩子区是否为空泛（无数字、无第一人称、无具体场景）
    has_ground = bool(re.search(r"\d|我|你|他|她|offer|公里|银行|面试|工作|岗位", window))
    if not has_ground:
        issues.append(Issue(
            "hook", "medium", path, 1,
            "开头缺少具体锚点",
            "钩子区内无数字、第一人称或具体场景词，读起来像概念导入",
        ))
    return issues


def check_ai_tag(path, lines):
    """AI 生成标注检测"""
    issues = []
    for i, l in enumerate(lines, 1):
        for m in AI_MARKERS:
            if m in l:
                issues.append(Issue(
                    "ai_tag", "medium", path, i,
                    f"检测到 AI 生成标注「{m}」",
                    "若为人工撰写，请移除该标注；AI 参与部分按平台规则标注",
                ))
                break
    return issues


def scan(path):
    p = Path(path)
    if not p.exists():
        print(f"文件不存在: {path}", file=sys.stderr)
        return []
    lines = p.read_text(encoding="utf-8").splitlines()
    title, tline = get_title(lines)
    issues = check_title(p, title, lines)
    # 标题行号可能不是 1
    for it in issues:
        if it.kind == "title":
            it.line = tline
    issues += check_hook(p, lines)
    issues += check_ai_tag(p, lines)
    return issues


def iter_docs():
    out = []
    for sub in ("连载", ""):
        d = DOCS / sub if sub else DOCS
        if not d.exists():
            continue
        for f in sorted(d.glob("*.md")):
            if sub == "" and "案例" not in f.name:
                continue
            if sub == "" and "连载" in f.name:
                continue
            out.append(f)
    seen, r = set(), []
    for f in out:
        if f.resolve() not in seen:
            seen.add(f.resolve())
            r.append(f)
    return r


def run(targets=None):
    files = [Path(t) for t in targets] if targets else iter_docs()
    issues = []
    for f in files:
        issues += scan(f)
    return issues


def report(issues, as_json=False):
    if as_json:
        print(json.dumps({
            "total": len(issues),
            "by_level": {
                lv: sum(1 for i in issues if i.level == lv)
                for lv in ("high", "medium")
            },
            "issues": [i.as_dict() for i in issues],
        }, ensure_ascii=False, indent=2))
        return 1 if any(i.level == "high" for i in issues) else 0

    high = [i for i in issues if i.level == "high"]
    mid = [i for i in issues if i.level == "medium"]

    print("\n" + "=" * 66)
    print(" 标题与钩子检查（A5 + A6）")
    print("=" * 66)

    if not issues:
        print("\n 全部通过 —— 标题均已场景化，开头均以场景切入\n")
        return 0

    for label, group in (("高风险", high), ("建议复核", mid)):
        if not group:
            continue
        print(f"\n[{label} · {len(group)} 项]")
        for i in group:
            mark = "✗" if i.level == "high" else "!"
            print(f"  {mark} {i.ref()}")
            print(f"      {i.msg}")
            if i.detail:
                print(f"      {i.detail}")
            print()

    print("-" * 66)
    print(f" 合计 {len(issues)} 项：高风险 {len(high)} / 建议复核 {len(mid)}")
    print("  说明：检查器只给风险信号，文学判断归作者\n")
    return 1 if high else 0


def main():
    argv = sys.argv[1:]
    as_json = "--json" in argv
    targets = [a for a in argv if not a.startswith("--")]
    if targets:
        missing = [t for t in targets if not Path(t).exists()]
        if missing:
            print(f"文件不存在: {', '.join(missing)}", file=sys.stderr)
            sys.exit(1)
    issues = run(targets)
    if not issues:
        if as_json:
            print(json.dumps({"total": 0, "issues": []}, ensure_ascii=False))
        else:
            print("\n未发现问题\n")
        sys.exit(0)
    sys.exit(report(issues, as_json))


if __name__ == "__main__":
    main()